#Datasource

quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: 1234
    jdbc:
      url: jdbc:postgresql://localhost:5432/customerdb

  hibernate-orm:
    database:
      generation: drop-and-create
