quarkus:
  http:
    port: 8081

  datasource:
    db-kind: postgresql
    username: postgres
    password: 1234
    jdbc:
      #url: jdbc:postgresql://db:5432/productdb
      url: jdbc:postgresql://localhost:5432/productdb
  hibernate-orm:
    database:
      generation: update

